# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 729234a545443ae8bedd4e65db1065a087adb7c30669e43c27aef403301823565f5cba46ed3bded6c50cce8eaab08859b3d948974387dda2b02e241d12da413b

test:
  secret_key_base: 7eb5ecfb15bdfdda6439a253a63a8764cba587946040319931feee30b86d63fb490ca10cef4f53a0079ba7e7d934665a10a1e934c09e684cba65073ee499c17e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
